// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'openapp://login-page',
];

class Routes {
  const Routes._();

  /// '登录页'
  ///
  /// [name] : 'openapp://login-page'
  ///
  /// [routeName] : '登录页'
  static const String openappLoginPage = 'openapp://login-page';
}
